import type { IndustryPack, Poi } from "@/core/types";
import { compileRules } from "./rules";

/**
 * A single-project vertical slice: one beachfront development, one location,
 * many unit types (condo / duplex / normal apartment) varying by bedrooms,
 * view (sea vs. main road) and private amenities (pool, jacuzzi, balcony) —
 * the exact "one project, many unit variations" shape a real developer like
 * Meliá Beachfront sells, as opposed to the flagship Real Estate pack's
 * "one agency, many separate properties across different areas." Every
 * question id below is deliberately identical to realEstatePack's own,
 * reusing the same real scoring engine, DiscoveryWizard grouping
 * (discoveryGroups.ts) and Decision Room/Recap surfaces unchanged — a new
 * vertical is proven here as configuration only, never a second engine.
 */
const POI_LAYOUT: Omit<Poi, "label" | "detail">[] = [
  { id: "school", icon: "GraduationCap", x: 53, y: 30, kind: "school" },
  { id: "park", icon: "Trees", x: 26, y: 35, kind: "park" },
  { id: "mall", icon: "ShoppingBag", x: 37, y: 18, kind: "shopping" },
  { id: "health", icon: "HeartPulse", x: 69, y: 22, kind: "health" },
  { id: "cafe", icon: "Coffee", x: 20, y: 49, kind: "leisure" },
  { id: "beach", icon: "Waves", x: 78, y: 44, kind: "water" },
  { id: "centre", icon: "TrainFront", x: 73, y: 64, kind: "transport" },
];

function pois(content: Record<string, [string, string]>): Poi[] {
  return POI_LAYOUT.map((p) => ({
    ...p,
    label: content[p.id][0],
    detail: content[p.id][1],
  }));
}

/** Every unit sits in the same building, so the surrounding lifestyle is identical — only the unit itself varies. */
const MELIA_POIS = pois({
  school: ["Nadeen School", "12 min"],
  park: ["Amwaj Lagoon Promenade", "4 min walk"],
  mall: ["Dragon City Mall", "10 min"],
  health: ["Bahrain Specialist Hospital", "15 min"],
  cafe: ["Beachfront Café Row", "In building"],
  beach: ["Meliá Private Lagoon Beach", "Ground floor"],
  centre: ["Bahrain International Airport", "8 min"],
});

export const meliaBeachfrontPack: IndustryPack = {
  id: "melia-beachfront",
  label: "Meliá Beachfront",
  vertical: "a single beachfront residential project — one building, many unit types",
  currency: "USD",
  branding: {
    name: "Meliá Beachfront",
    tagline: "One address. Every way to live by the sea.",
    brand: "20 108 148", // deep sea teal
    brandSoft: "125 211 252", // sky blue
    logoGlyph: "🌊",
  },
  sections: [
    { id: "household", label: "Household" },
    { id: "location", label: "Location" },
    { id: "home", label: "The Unit" },
    { id: "intent", label: "Intent" },
    { id: "lifestyle", label: "Lifestyle" },
    { id: "financial", label: "Financial" },
    { id: "timing", label: "Timing" },
  ],
  questions: [
    {
      id: "household",
      label: "Household",
      prompt: "Who is this home for?",
      type: "single",
      section: "household",
      options: [
        { id: "single", label: "Single", icon: "User" },
        { id: "couple", label: "Couple", icon: "Users" },
        { id: "family", label: "Family", icon: "Home" },
      ],
    },
    {
      id: "familySize",
      label: "Family size",
      prompt: "How many people will live here?",
      type: "counter",
      section: "household",
      min: 1,
      max: 8,
      showWhen: { questionId: "household", op: "eq", value: "family" },
    },
    {
      id: "budget",
      label: "Budget",
      prompt: "What budget are we working with?",
      type: "budget",
      section: "household",
      min: 200000,
      max: 1100000,
      step: 10000,
      unit: "USD",
      weight: 3,
    },
    {
      id: "bedrooms",
      label: "Bedrooms",
      prompt: "How many bedrooms do you need?",
      type: "counter",
      section: "home",
      min: 1,
      max: 4,
    },
    {
      id: "workLocation",
      label: "Workplace",
      prompt: "Where do they work?",
      type: "text",
      section: "location",
    },
    {
      id: "schools",
      label: "Near schools",
      prompt: "Should we prioritise nearby schools?",
      type: "toggle",
      section: "location",
    },
    {
      id: "seaView",
      label: "Sea view",
      prompt: "Is a sea view important to you?",
      type: "toggle",
      section: "location",
    },
    {
      id: "garden",
      label: "Garden",
      prompt: "Would you like a private garden?",
      type: "toggle",
      section: "home",
    },
    {
      id: "quiet",
      label: "Quiet area",
      prompt: "Do you prefer to be away from the main road?",
      type: "toggle",
      section: "location",
    },
    {
      id: "intent",
      label: "Intent",
      prompt: "What matters most about this purchase?",
      type: "multi",
      section: "intent",
      options: [
        { id: "living", label: "To live in", icon: "Heart" },
        { id: "investment", label: "Investment", icon: "TrendingUp" },
        { id: "rental", label: "Rental income", icon: "Coins" },
        { id: "luxury", label: "Luxury", icon: "Sparkles" },
      ],
    },
    {
      id: "destinationType",
      label: "Destination",
      prompt: "Where does your day take you?",
      type: "single",
      section: "location",
      options: [
        { id: "work", label: "Work", icon: "Briefcase" },
        { id: "school", label: "School", icon: "GraduationCap" },
        { id: "family", label: "Family", icon: "Users" },
        { id: "other", label: "Other", icon: "MapPin" },
      ],
    },
    {
      id: "commuteImportance",
      label: "Commute importance",
      prompt: "How important is the commute?",
      type: "single",
      section: "location",
      options: [
        { id: "veryImportant", label: "Very important" },
        { id: "important", label: "Important" },
        { id: "flexible", label: "Flexible" },
      ],
    },
    {
      id: "maxCommute",
      label: "Maximum commute",
      prompt: "What's the maximum commute?",
      type: "single",
      section: "location",
      options: [
        { id: "15", label: "15 min" },
        { id: "30", label: "30 min" },
        { id: "45", label: "45 min" },
        { id: "60plus", label: "60 min+" },
        { id: "noPreference", label: "No preference" },
      ],
    },
    {
      id: "nearbyPreferences",
      label: "Nearby preferences",
      prompt: "What should be close by?",
      type: "multi",
      section: "location",
      options: [
        { id: "schools", label: "Schools", icon: "GraduationCap" },
        { id: "hospitals", label: "Hospitals", icon: "HeartPulse" },
        { id: "supermarkets", label: "Supermarkets", icon: "ShoppingCart" },
        { id: "highway", label: "Highway", icon: "Route" },
        { id: "university", label: "University", icon: "Landmark" },
        { id: "beach", label: "Beach", icon: "Waves" },
        { id: "shopping", label: "Shopping", icon: "ShoppingBag" },
        { id: "restaurants", label: "Restaurants", icon: "UtensilsCrossed" },
        { id: "workplace", label: "Workplace", icon: "Briefcase" },
        { id: "family", label: "Family", icon: "Users" },
        { id: "publicTransport", label: "Public transport", icon: "TrainFront" },
        { id: "other", label: "Other", icon: "MoreHorizontal" },
      ],
    },
    {
      id: "locationImportance",
      label: "Location importance",
      prompt: "How important is location?",
      type: "single",
      section: "location",
      options: [
        { id: "essential", label: "Essential" },
        { id: "important", label: "Important" },
        { id: "niceToHave", label: "Nice to have" },
        { id: "notImportant", label: "Not important" },
      ],
    },
    {
      id: "propertyType",
      label: "Unit type",
      prompt: "What kind of unit are we looking for?",
      type: "multi",
      section: "home",
      options: [
        { id: "apartment", label: "Normal apartment", icon: "Building2" },
        { id: "condo", label: "Condo", icon: "Building" },
        { id: "duplex", label: "Duplex", icon: "Layers" },
        { id: "openToOptions", label: "Open to options", icon: "Sparkles" },
      ],
    },
    {
      id: "lifestyleStyle",
      label: "Lifestyle",
      prompt: "What does home need to feel like?",
      type: "multi",
      section: "lifestyle",
      options: [
        { id: "family", label: "Family", icon: "Home" },
        { id: "luxury", label: "Luxury", icon: "Sparkles" },
        { id: "quiet", label: "Quiet", icon: "Moon" },
        { id: "social", label: "Social", icon: "Users" },
        { id: "investment", label: "Investment", icon: "TrendingUp" },
        { id: "beachWaterfront", label: "Beach / Waterfront", icon: "Waves" },
        { id: "modern", label: "Modern", icon: "Sparkle" },
      ],
    },
    {
      id: "homeFeatures",
      label: "Unit features",
      prompt: "What would make the unit feel right?",
      type: "multi",
      section: "home",
      options: [
        { id: "pool", label: "Private pool", icon: "Waves" },
        { id: "jacuzzi", label: "Private jacuzzi", icon: "Droplets" },
        { id: "balcony", label: "Balcony", icon: "DoorOpen" },
        { id: "largeTerrace", label: "Large terrace", icon: "Square" },
        { id: "seaView", label: "Sea view", icon: "Waves" },
        { id: "mainRoadView", label: "Main road view", icon: "Route" },
        { id: "parking", label: "Parking", icon: "Car" },
        { id: "storage", label: "Storage", icon: "Package" },
        { id: "highFloor", label: "High floor", icon: "ArrowUp" },
        { id: "smartHome", label: "Smart home", icon: "Cpu" },
        { id: "other", label: "Other", icon: "MoreHorizontal" },
      ],
    },
    {
      id: "purchaseMethod",
      label: "Purchase method",
      prompt: "How would you like to purchase?",
      type: "single",
      section: "financial",
      options: [
        { id: "cash", label: "Cash", icon: "Banknote" },
        { id: "financing", label: "Financing", icon: "Landmark" },
        { id: "notDecided", label: "Not decided", icon: "HelpCircle" },
      ],
    },
    {
      id: "monthlyPayment",
      label: "Monthly payment",
      prompt: "Do they have a preferred monthly payment or financing range?",
      type: "text",
      section: "financial",
      showWhen: { questionId: "purchaseMethod", op: "eq", value: "financing" },
    },
    {
      id: "timing",
      label: "Timing",
      prompt: "When are you looking to move?",
      type: "single",
      section: "timing",
      options: [
        { id: "now", label: "Now" },
        { id: "threeMonths", label: "3 months" },
        { id: "sixMonths", label: "6 months" },
        { id: "thisYear", label: "This year" },
        { id: "exploring", label: "Exploring" },
      ],
    },
  ],
  inventory: [
    {
      id: "melia-101",
      name: "Meliá Beachfront · Unit 101",
      subtitle: "1-bed condo · Main road view",
      price: 220000,
      currency: "USD",
      image: "amber",
      location: { label: "Amwaj Islands", lat: 26.317, lng: 50.652 },
      photo: "/industries/melia-beachfront/building/hero.png",
      gallery: [
        "/industries/melia-beachfront/building/gallery-detail.png",
        "/industries/melia-beachfront/building/gallery-twilight.png",
        "/industries/melia-beachfront/building/gallery-texture.png",
      ],
      appreciation: 9,
      attributes: {
        bedrooms: 1,
        schools: 1,
        schoolMinutes: 12,
        garden: false,
        seaView: false,
        quiet: false,
        plotSize: 0,
        unitType: "condo",
        pool: false,
        jacuzzi: false,
        balcony: true,
      },
      highlights: ["Entry-level price for the building", "Balcony over the courtyard", "Ground-floor café access"],
      lifestyle: {
        district: "Meliá Beachfront, Amwaj Islands",
        tags: ["Compact", "Investment", "Entry-level"],
        summary: "The building's most accessible unit — full access to every shared amenity at the lowest entry price.",
        beds: 1,
        sqm: 58,
        at: { x: 45, y: 43 },
        metrics: [
          { icon: "Waves", label: "Beach", detail: "Ground floor" },
          { icon: "GraduationCap", label: "Schools", detail: "9 min" },
          { icon: "TrainFront", label: "Marina", detail: "6 min walk" },
        ],
        pois: MELIA_POIS,
      },
    },
    {
      id: "melia-204",
      name: "Meliá Beachfront · Unit 204",
      subtitle: "2-bed condo · Sea view",
      price: 340000,
      currency: "USD",
      image: "sky",
      location: { label: "Amwaj Islands", lat: 26.317, lng: 50.652 },
      photo: "/industries/melia-beachfront/building/hero.png",
      gallery: [
        "/industries/melia-beachfront/building/gallery-detail.png",
        "/industries/melia-beachfront/building/gallery-twilight.png",
        "/industries/melia-beachfront/building/gallery-texture.png",
      ],
      appreciation: 14,
      attributes: {
        bedrooms: 2,
        schools: 1,
        schoolMinutes: 12,
        garden: false,
        seaView: true,
        quiet: true,
        plotSize: 0,
        unitType: "condo",
        pool: false,
        jacuzzi: false,
        balcony: true,
      },
      highlights: ["Uninterrupted sea view", "Away from the main road", "Wide wraparound balcony"],
      lifestyle: {
        district: "Meliá Beachfront, Amwaj Islands",
        tags: ["Sea view", "Quiet", "Balcony"],
        summary: "A second-floor condo facing the water, quiet side of the building.",
        beds: 2,
        sqm: 92,
        at: { x: 45, y: 43 },
        metrics: [
          { icon: "Waves", label: "Beach", detail: "Ground floor" },
          { icon: "GraduationCap", label: "Schools", detail: "9 min" },
          { icon: "TrainFront", label: "Marina", detail: "6 min walk" },
        ],
        pois: MELIA_POIS,
      },
    },
    {
      id: "melia-305",
      name: "Meliá Beachfront · Unit 305",
      subtitle: "2-bed apartment · Main road view",
      price: 295000,
      currency: "USD",
      image: "amber",
      location: { label: "Amwaj Islands", lat: 26.317, lng: 50.652 },
      photo: "/industries/melia-beachfront/building/hero.png",
      gallery: [
        "/industries/melia-beachfront/building/gallery-detail.png",
        "/industries/melia-beachfront/building/gallery-twilight.png",
        "/industries/melia-beachfront/building/gallery-texture.png",
      ],
      appreciation: 10,
      attributes: {
        bedrooms: 2,
        schools: 1,
        schoolMinutes: 12,
        garden: false,
        seaView: false,
        quiet: false,
        plotSize: 0,
        unitType: "apartment",
        pool: false,
        jacuzzi: false,
        balcony: true,
      },
      highlights: ["Best value 2-bed in the building", "Balcony over the boulevard", "Full building amenities included"],
      lifestyle: {
        district: "Meliá Beachfront, Amwaj Islands",
        tags: ["Value", "Family", "Balcony"],
        summary: "A straightforward, well-priced apartment facing the main boulevard.",
        beds: 2,
        sqm: 88,
        at: { x: 45, y: 43 },
        metrics: [
          { icon: "Waves", label: "Beach", detail: "Ground floor" },
          { icon: "GraduationCap", label: "Schools", detail: "9 min" },
          { icon: "TrainFront", label: "Marina", detail: "6 min walk" },
        ],
        pois: MELIA_POIS,
      },
    },
    {
      id: "melia-402",
      name: "Meliá Beachfront · Unit 402",
      subtitle: "3-bed duplex · Sea view · Jacuzzi",
      price: 580000,
      currency: "USD",
      image: "violet",
      location: { label: "Amwaj Islands", lat: 26.317, lng: 50.652 },
      photo: "/industries/melia-beachfront/building/hero.png",
      gallery: [
        "/industries/melia-beachfront/building/gallery-detail.png",
        "/industries/melia-beachfront/building/gallery-twilight.png",
        "/industries/melia-beachfront/building/gallery-texture.png",
      ],
      appreciation: 17,
      attributes: {
        bedrooms: 3,
        schools: 1,
        schoolMinutes: 12,
        garden: false,
        seaView: true,
        quiet: true,
        plotSize: 0,
        unitType: "duplex",
        pool: false,
        jacuzzi: true,
        balcony: true,
      },
      highlights: ["Two-level duplex layout", "Private rooftop jacuzzi", "Panoramic sea view from both floors"],
      lifestyle: {
        district: "Meliá Beachfront, Amwaj Islands",
        tags: ["Duplex", "Luxury", "Sea view"],
        summary: "A two-storey duplex with its own rooftop jacuzzi terrace overlooking the water.",
        beds: 3,
        sqm: 165,
        at: { x: 45, y: 43 },
        metrics: [
          { icon: "Waves", label: "Beach", detail: "Ground floor" },
          { icon: "GraduationCap", label: "Schools", detail: "9 min" },
          { icon: "TrainFront", label: "Marina", detail: "6 min walk" },
        ],
        pois: MELIA_POIS,
      },
    },
    {
      id: "melia-501",
      name: "Meliá Beachfront · Unit 501",
      subtitle: "3-bed apartment · Sea view",
      price: 460000,
      currency: "USD",
      image: "sky",
      location: { label: "Amwaj Islands", lat: 26.317, lng: 50.652 },
      photo: "/industries/melia-beachfront/building/hero.png",
      gallery: [
        "/industries/melia-beachfront/building/gallery-detail.png",
        "/industries/melia-beachfront/building/gallery-twilight.png",
        "/industries/melia-beachfront/building/gallery-texture.png",
      ],
      appreciation: 15,
      attributes: {
        bedrooms: 3,
        schools: 1,
        schoolMinutes: 12,
        garden: false,
        seaView: true,
        quiet: true,
        plotSize: 0,
        unitType: "apartment",
        pool: false,
        jacuzzi: false,
        balcony: true,
      },
      highlights: ["Full-floor sea views", "Family-sized layout", "Top-of-building quiet side"],
      lifestyle: {
        district: "Meliá Beachfront, Amwaj Islands",
        tags: ["Family", "Sea view", "Quiet"],
        summary: "A fifth-floor family apartment on the quiet, sea-facing side of the building.",
        beds: 3,
        sqm: 142,
        at: { x: 45, y: 43 },
        metrics: [
          { icon: "Waves", label: "Beach", detail: "Ground floor" },
          { icon: "GraduationCap", label: "Schools", detail: "9 min" },
          { icon: "TrainFront", label: "Marina", detail: "6 min walk" },
        ],
        pois: MELIA_POIS,
      },
    },
    {
      id: "melia-606",
      name: "Meliá Beachfront · Unit 606",
      subtitle: "2-bed condo · Main road view",
      price: 260000,
      currency: "USD",
      image: "amber",
      location: { label: "Amwaj Islands", lat: 26.317, lng: 50.652 },
      photo: "/industries/melia-beachfront/building/hero.png",
      gallery: [
        "/industries/melia-beachfront/building/gallery-detail.png",
        "/industries/melia-beachfront/building/gallery-twilight.png",
        "/industries/melia-beachfront/building/gallery-texture.png",
      ],
      appreciation: 8,
      attributes: {
        bedrooms: 2,
        schools: 1,
        schoolMinutes: 12,
        garden: false,
        seaView: false,
        quiet: false,
        plotSize: 0,
        unitType: "condo",
        pool: false,
        jacuzzi: false,
        balcony: false,
      },
      highlights: ["Lowest-priced 2-bed in the building", "Strong rental yield profile", "No balcony — priced accordingly"],
      lifestyle: {
        district: "Meliá Beachfront, Amwaj Islands",
        tags: ["Investment", "Rental", "Value"],
        summary: "A no-frills investment unit facing the main road, priced to move.",
        beds: 2,
        sqm: 80,
        at: { x: 45, y: 43 },
        metrics: [
          { icon: "Waves", label: "Beach", detail: "Ground floor" },
          { icon: "GraduationCap", label: "Schools", detail: "9 min" },
          { icon: "TrainFront", label: "Marina", detail: "6 min walk" },
        ],
        pois: MELIA_POIS,
      },
    },
    {
      id: "melia-210",
      name: "Meliá Beachfront · Unit 210",
      subtitle: "3-bed duplex · Main road view · Jacuzzi",
      price: 520000,
      currency: "USD",
      image: "violet",
      location: { label: "Amwaj Islands", lat: 26.317, lng: 50.652 },
      photo: "/industries/melia-beachfront/building/hero.png",
      gallery: [
        "/industries/melia-beachfront/building/gallery-detail.png",
        "/industries/melia-beachfront/building/gallery-twilight.png",
        "/industries/melia-beachfront/building/gallery-texture.png",
      ],
      appreciation: 12,
      attributes: {
        bedrooms: 3,
        schools: 1,
        schoolMinutes: 12,
        garden: false,
        seaView: false,
        quiet: false,
        plotSize: 0,
        unitType: "duplex",
        pool: false,
        jacuzzi: true,
        balcony: true,
      },
      highlights: ["Duplex layout without the sea-view premium", "Private jacuzzi terrace", "Best duplex value in the building"],
      lifestyle: {
        district: "Meliá Beachfront, Amwaj Islands",
        tags: ["Duplex", "Value", "Jacuzzi"],
        summary: "The same duplex layout as the sea-view units, at a lower price on the road-facing side.",
        beds: 3,
        sqm: 160,
        at: { x: 45, y: 43 },
        metrics: [
          { icon: "Waves", label: "Beach", detail: "Ground floor" },
          { icon: "GraduationCap", label: "Schools", detail: "9 min" },
          { icon: "TrainFront", label: "Marina", detail: "6 min walk" },
        ],
        pois: MELIA_POIS,
      },
    },
    {
      id: "melia-108",
      name: "Meliá Beachfront · Unit 108",
      subtitle: "2-bed apartment · Main road view",
      price: 275000,
      currency: "USD",
      image: "amber",
      location: { label: "Amwaj Islands", lat: 26.317, lng: 50.652 },
      photo: "/industries/melia-beachfront/building/hero.png",
      gallery: [
        "/industries/melia-beachfront/building/gallery-detail.png",
        "/industries/melia-beachfront/building/gallery-twilight.png",
        "/industries/melia-beachfront/building/gallery-texture.png",
      ],
      appreciation: 8,
      attributes: {
        bedrooms: 2,
        schools: 1,
        schoolMinutes: 12,
        garden: false,
        seaView: false,
        quiet: false,
        plotSize: 0,
        unitType: "apartment",
        pool: false,
        jacuzzi: false,
        balcony: true,
      },
      highlights: ["Ground-floor convenience", "Direct courtyard access", "Balcony onto the boulevard"],
      lifestyle: {
        district: "Meliá Beachfront, Amwaj Islands",
        tags: ["Value", "Accessible"],
        summary: "A ground-floor unit with easy access, facing the main road.",
        beds: 2,
        sqm: 84,
        at: { x: 45, y: 43 },
        metrics: [
          { icon: "Waves", label: "Beach", detail: "Ground floor" },
          { icon: "GraduationCap", label: "Schools", detail: "9 min" },
          { icon: "TrainFront", label: "Marina", detail: "6 min walk" },
        ],
        pois: MELIA_POIS,
      },
    },
    {
      id: "melia-302",
      name: "Meliá Beachfront · Unit 302",
      subtitle: "1-bed condo · Sea view",
      price: 310000,
      currency: "USD",
      image: "sky",
      location: { label: "Amwaj Islands", lat: 26.317, lng: 50.652 },
      photo: "/industries/melia-beachfront/building/hero.png",
      gallery: [
        "/industries/melia-beachfront/building/gallery-detail.png",
        "/industries/melia-beachfront/building/gallery-twilight.png",
        "/industries/melia-beachfront/building/gallery-texture.png",
      ],
      appreciation: 13,
      attributes: {
        bedrooms: 1,
        schools: 1,
        schoolMinutes: 12,
        garden: false,
        seaView: true,
        quiet: true,
        plotSize: 0,
        unitType: "condo",
        pool: false,
        jacuzzi: false,
        balcony: true,
      },
      highlights: ["Compact luxury with a full sea view", "Popular short-let profile", "Quiet, sea-facing side"],
      lifestyle: {
        district: "Meliá Beachfront, Amwaj Islands",
        tags: ["Compact", "Sea view", "Rental"],
        summary: "A small but premium sea-view unit, popular with short-let investors.",
        beds: 1,
        sqm: 62,
        at: { x: 45, y: 43 },
        metrics: [
          { icon: "Waves", label: "Beach", detail: "Ground floor" },
          { icon: "GraduationCap", label: "Schools", detail: "9 min" },
          { icon: "TrainFront", label: "Marina", detail: "6 min walk" },
        ],
        pois: MELIA_POIS,
      },
    },
    {
      id: "melia-701",
      name: "Meliá Beachfront · Unit 701",
      subtitle: "4-bed duplex penthouse · Sea view · Pool & jacuzzi",
      price: 890000,
      currency: "USD",
      image: "violet",
      location: { label: "Amwaj Islands", lat: 26.317, lng: 50.652 },
      photo: "/industries/melia-beachfront/building/hero.png",
      gallery: [
        "/industries/melia-beachfront/building/gallery-detail.png",
        "/industries/melia-beachfront/building/gallery-twilight.png",
        "/industries/melia-beachfront/building/gallery-texture.png",
      ],
      appreciation: 19,
      attributes: {
        bedrooms: 4,
        schools: 1,
        schoolMinutes: 12,
        garden: false,
        seaView: true,
        quiet: true,
        plotSize: 0,
        unitType: "duplex",
        pool: true,
        jacuzzi: true,
        balcony: true,
      },
      highlights: ["Top-floor duplex penthouse", "Private rooftop pool and jacuzzi", "360° sea and marina views"],
      lifestyle: {
        district: "Meliá Beachfront, Amwaj Islands",
        tags: ["Penthouse", "Luxury", "Sea view"],
        summary: "The building's signature duplex penthouse, with a private rooftop pool and jacuzzi.",
        beds: 4,
        sqm: 240,
        at: { x: 45, y: 43 },
        metrics: [
          { icon: "Waves", label: "Beach", detail: "Ground floor" },
          { icon: "GraduationCap", label: "Schools", detail: "9 min" },
          { icon: "TrainFront", label: "Marina", detail: "6 min walk" },
        ],
        pois: MELIA_POIS,
      },
    },
    {
      id: "melia-604",
      name: "Meliá Beachfront · Unit 604",
      subtitle: "3-bed condo · Sea view",
      price: 505000,
      currency: "USD",
      image: "sky",
      location: { label: "Amwaj Islands", lat: 26.317, lng: 50.652 },
      photo: "/industries/melia-beachfront/building/hero.png",
      gallery: [
        "/industries/melia-beachfront/building/gallery-detail.png",
        "/industries/melia-beachfront/building/gallery-twilight.png",
        "/industries/melia-beachfront/building/gallery-texture.png",
      ],
      appreciation: 16,
      attributes: {
        bedrooms: 3,
        schools: 1,
        schoolMinutes: 12,
        garden: false,
        seaView: true,
        quiet: true,
        plotSize: 0,
        unitType: "condo",
        pool: false,
        jacuzzi: false,
        balcony: true,
      },
      highlights: ["High-floor sea view", "Family-sized condo", "Quiet, sea-facing side"],
      lifestyle: {
        district: "Meliá Beachfront, Amwaj Islands",
        tags: ["Family", "Sea view", "High floor"],
        summary: "A high-floor, sea-facing condo sized for a family.",
        beds: 3,
        sqm: 138,
        at: { x: 45, y: 43 },
        metrics: [
          { icon: "Waves", label: "Beach", detail: "Ground floor" },
          { icon: "GraduationCap", label: "Schools", detail: "9 min" },
          { icon: "TrainFront", label: "Marina", detail: "6 min walk" },
        ],
        pois: MELIA_POIS,
      },
    },
    {
      id: "melia-801",
      name: "Meliá Beachfront · Unit 801",
      subtitle: "4-bed duplex · Main road view · Pool & jacuzzi",
      price: 1050000,
      currency: "USD",
      image: "violet",
      location: { label: "Amwaj Islands", lat: 26.317, lng: 50.652 },
      photo: "/industries/melia-beachfront/building/hero.png",
      gallery: [
        "/industries/melia-beachfront/building/gallery-detail.png",
        "/industries/melia-beachfront/building/gallery-twilight.png",
        "/industries/melia-beachfront/building/gallery-texture.png",
      ],
      appreciation: 18,
      attributes: {
        bedrooms: 4,
        schools: 1,
        schoolMinutes: 12,
        garden: false,
        seaView: false,
        quiet: false,
        plotSize: 0,
        unitType: "duplex",
        pool: true,
        jacuzzi: true,
        balcony: true,
      },
      highlights: ["Largest unit in the building", "Private rooftop pool and jacuzzi", "Full-floor duplex layout"],
      lifestyle: {
        district: "Meliá Beachfront, Amwaj Islands",
        tags: ["Penthouse", "Luxury", "Largest unit"],
        summary: "The building's largest duplex, on the boulevard-facing side, with its own rooftop pool and jacuzzi.",
        beds: 4,
        sqm: 265,
        at: { x: 45, y: 43 },
        metrics: [
          { icon: "Waves", label: "Beach", detail: "Ground floor" },
          { icon: "GraduationCap", label: "Schools", detail: "9 min" },
          { icon: "TrainFront", label: "Marina", detail: "6 min walk" },
        ],
        pois: MELIA_POIS,
      },
    },
  ],
  ruleSpecs: [
    { id: "budget-fit", kind: "budget", questionId: "budget", weight: 3 },
    {
      id: "bedrooms-min",
      kind: "atLeast",
      questionId: "bedrooms",
      attribute: "bedrooms",
      weight: 2.5,
      reason: "it offers {have} bedrooms, meeting your need for {need}",
    },
    {
      id: "sea-view",
      kind: "feature",
      questionId: "seaView",
      attribute: "seaView",
      weight: 2.5,
      reason: "it has the sea view you asked for",
    },
    {
      id: "quiet",
      kind: "feature",
      questionId: "quiet",
      attribute: "quiet",
      weight: 1.5,
      reason: "it faces away from the main road",
    },
    { id: "investment", kind: "investment", questionId: "intent", weight: 2.5 },
  ],
  rules: [],
};

meliaBeachfrontPack.rules = compileRules(meliaBeachfrontPack.ruleSpecs!);
