import type { IndustryPack } from "@/core/types";
import {
  atLeastRule,
  budgetRule,
  featureRule,
  investmentRule,
  proximityRule,
} from "./rules";

export const realEstatePack: IndustryPack = {
  id: "real-estate",
  label: "Real Estate",
  vertical: "residential real estate development",
  currency: "USD",
  branding: {
    name: "Green Hills Living",
    tagline: "Find the home your life is asking for.",
    brand: "16 185 129", // emerald
    brandSoft: "52 211 153",
    logoGlyph: "◈",
  },
  sections: [
    { id: "household", label: "Household" },
    { id: "location", label: "Location" },
    { id: "home", label: "The Home" },
    { id: "intent", label: "Intent" },
  ],
  questions: [
    {
      id: "household",
      label: "Household",
      prompt: "Who is this home for?",
      type: "single",
      section: "household",
      options: [
        { id: "single", label: "Single", icon: "User" },
        { id: "couple", label: "Couple", icon: "Users" },
        { id: "family", label: "Family", icon: "Home" },
      ],
    },
    {
      id: "familySize",
      label: "Family size",
      prompt: "How many people will live here?",
      type: "counter",
      section: "household",
      min: 1,
      max: 8,
      showWhen: { questionId: "household", op: "eq", value: "family" },
    },
    {
      id: "budget",
      label: "Budget",
      prompt: "What budget are we working with?",
      type: "budget",
      section: "household",
      min: 100000,
      max: 800000,
      step: 10000,
      unit: "USD",
      weight: 3,
    },
    {
      id: "bedrooms",
      label: "Bedrooms",
      prompt: "How many bedrooms do you need?",
      type: "counter",
      section: "home",
      min: 1,
      max: 6,
    },
    {
      id: "schools",
      label: "Near schools",
      prompt: "Should we prioritise nearby schools?",
      type: "toggle",
      section: "location",
    },
    {
      id: "seaView",
      label: "Sea view",
      prompt: "Is a sea view important to you?",
      type: "toggle",
      section: "location",
    },
    {
      id: "garden",
      label: "Garden",
      prompt: "Would you like a private garden?",
      type: "toggle",
      section: "home",
    },
    {
      id: "quiet",
      label: "Quiet area",
      prompt: "Do you prefer a quiet neighbourhood?",
      type: "toggle",
      section: "location",
    },
    {
      id: "intent",
      label: "Intent",
      prompt: "What matters most about this purchase?",
      type: "multi",
      section: "intent",
      options: [
        { id: "living", label: "To live in", icon: "Heart" },
        { id: "investment", label: "Investment", icon: "TrendingUp" },
        { id: "rental", label: "Rental income", icon: "Coins" },
        { id: "luxury", label: "Luxury", icon: "Sparkles" },
      ],
    },
  ],
  inventory: [
    {
      id: "green-hills",
      name: "Green Hills",
      subtitle: "Garden townhouses · Larnaca",
      price: 285000,
      currency: "USD",
      image: "emerald",
      location: { label: "Larnaca", lat: 34.92, lng: 33.62 },
      appreciation: 18,
      attributes: {
        bedrooms: 4,
        schools: 3,
        schoolMinutes: 5,
        garden: true,
        seaView: false,
        quiet: true,
        plotSize: 420,
      },
      highlights: [
        "3 international schools within 5 min",
        "Larger plots than comparable projects",
        "18% appreciation over 3 years",
      ],
    },
    {
      id: "marina-vista",
      name: "Marina Vista",
      subtitle: "Sea-view apartments · Limassol",
      price: 520000,
      currency: "USD",
      image: "sky",
      location: { label: "Limassol", lat: 34.68, lng: 33.04 },
      appreciation: 12,
      attributes: {
        bedrooms: 3,
        schools: 1,
        schoolMinutes: 14,
        garden: false,
        seaView: true,
        quiet: false,
        plotSize: 0,
      },
      highlights: [
        "Panoramic marina & sea views",
        "Walk to the promenade",
        "Premium rental demand",
      ],
    },
    {
      id: "olive-grove",
      name: "Olive Grove",
      subtitle: "Village villas · Paphos hills",
      price: 240000,
      currency: "USD",
      image: "amber",
      location: { label: "Paphos", lat: 34.77, lng: 32.42 },
      appreciation: 9,
      attributes: {
        bedrooms: 3,
        schools: 2,
        schoolMinutes: 9,
        garden: true,
        seaView: false,
        quiet: true,
        plotSize: 610,
      },
      highlights: [
        "Largest gardens in the portfolio",
        "Peaceful hillside setting",
        "Excellent value per m²",
      ],
    },
    {
      id: "azure-residences",
      name: "Azure Residences",
      subtitle: "Luxury penthouses · Limassol",
      price: 740000,
      currency: "USD",
      image: "violet",
      location: { label: "Limassol", lat: 34.7, lng: 33.02 },
      appreciation: 15,
      attributes: {
        bedrooms: 5,
        schools: 2,
        schoolMinutes: 8,
        garden: false,
        seaView: true,
        quiet: false,
        plotSize: 0,
      },
      highlights: [
        "Signature rooftop & concierge",
        "Sea views from every room",
        "Flagship luxury address",
      ],
    },
  ],
  rules: [
    budgetRule("budget", 3),
    atLeastRule(
      "bedrooms",
      "bedrooms",
      (need, have) => `it offers ${have} bedrooms, meeting your need for ${need}`,
      2.5,
    ),
    proximityRule("schools", "schoolMinutes", {
      ceiling: 15,
      weight: 2.5,
      reason: (v) => `it has international schools within ${v} minutes`,
    }),
    featureRule("seaView", "seaView", "it has the sea view you asked for", 2),
    featureRule("garden", "garden", "it comes with a private garden", 2),
    featureRule("quiet", "quiet", "it sits in a quiet neighbourhood", 1.5),
    investmentRule("intent", 2.5),
  ],
};
