import type { IndustryPack } from "@/core/types";
import { compileRules } from "./rules";

export const yachtPack: IndustryPack = {
  id: "yacht",
  label: "Yacht Charter",
  vertical: "luxury yacht charter and brokerage",
  currency: "USD",
  branding: {
    name: "Meridian Yachts",
    tagline: "Charter the horizon.",
    brand: "20 184 166", // teal
    brandSoft: "45 212 191",
    logoGlyph: "⛵",
  },
  sections: [
    { id: "trip", label: "Trip" },
    { id: "budget", label: "Budget" },
    { id: "preferences", label: "Preferences" },
  ],
  questions: [
    {
      id: "occasion",
      label: "Occasion",
      prompt: "What's the occasion for this charter?",
      type: "single",
      section: "trip",
      options: [
        { id: "family", label: "Family holiday", icon: "Users" },
        { id: "corporate", label: "Corporate charter", icon: "Briefcase" },
        { id: "event", label: "Special event", icon: "PartyPopper" },
        { id: "islands", label: "Island hopping", icon: "Map" },
      ],
    },
    {
      id: "guests",
      label: "Guests",
      prompt: "How many guests will be aboard?",
      type: "counter",
      section: "trip",
      min: 2,
      max: 20,
    },
    {
      id: "days",
      label: "Trip length",
      prompt: "How many days is the charter?",
      type: "slider",
      section: "trip",
      min: 3,
      max: 21,
      step: 1,
      unit: "days",
    },
    {
      id: "budget",
      label: "Budget",
      prompt: "What's your weekly charter budget?",
      type: "budget",
      section: "budget",
      min: 15000,
      max: 500000,
      step: 5000,
      unit: "USD",
      weight: 3,
    },
    {
      id: "crewed",
      label: "Fully crewed",
      prompt: "Would you like a fully crewed charter?",
      type: "toggle",
      section: "preferences",
    },
    {
      id: "waterToys",
      label: "Water toys",
      prompt: "Is a water toys package important to you?",
      type: "toggle",
      section: "preferences",
    },
  ],
  inventory: [
    {
      id: "azure-breeze",
      name: "Azure Breeze",
      subtitle: "42m motor yacht · Mediterranean",
      price: 180000,
      currency: "USD",
      image: "sky",
      photo: "/industries/yacht/azure-breeze/hero.png",
      gallery: [
        "/industries/yacht/azure-breeze/gallery-detail.png",
        "/industries/yacht/azure-breeze/gallery-twilight.png",
        "/industries/yacht/azure-breeze/gallery-texture.png",
      ],
      appreciation: 0,
      attributes: {
        length: 42,
        guests: 12,
        cabins: 6,
        crewed: true,
        waterToys: true,
        crewSize: 9,
      },
      highlights: ["9-person professional crew", "Full water toys package", "6 en-suite cabins"],
    },
    {
      id: "wind-dancer",
      name: "Wind Dancer",
      subtitle: "24m sailing yacht · Aegean",
      price: 65000,
      currency: "USD",
      image: "emerald",
      photo: "/industries/yacht/wind-dancer/hero.png",
      gallery: [
        "/industries/yacht/wind-dancer/gallery-detail.png",
        "/industries/yacht/wind-dancer/gallery-twilight.png",
        "/industries/yacht/wind-dancer/gallery-texture.png",
      ],
      appreciation: 0,
      attributes: {
        length: 24,
        guests: 8,
        cabins: 4,
        crewed: true,
        waterToys: false,
        crewSize: 4,
      },
      highlights: ["Classic sailing experience", "Intimate 4-cabin layout", "Expert sailing crew"],
    },
    {
      id: "meridian-one",
      name: "Meridian One",
      subtitle: "55m superyacht · Caribbean",
      price: 420000,
      currency: "USD",
      image: "violet",
      photo: "/industries/yacht/meridian-one/hero.png",
      gallery: [
        "/industries/yacht/meridian-one/gallery-detail.png",
        "/industries/yacht/meridian-one/gallery-twilight.png",
        "/industries/yacht/meridian-one/gallery-texture.png",
      ],
      appreciation: 0,
      attributes: {
        length: 55,
        guests: 16,
        cabins: 8,
        crewed: true,
        waterToys: true,
        crewSize: 18,
      },
      highlights: ["Flagship superyacht", "Beach club & helipad", "18-person crew, full toy garage"],
    },
    {
      id: "coastal-spirit",
      name: "Coastal Spirit",
      subtitle: "18m motor yacht · Adriatic",
      price: 22000,
      currency: "USD",
      image: "amber",
      photo: "/industries/yacht/coastal-spirit/hero.png",
      gallery: [
        "/industries/yacht/coastal-spirit/gallery-detail.png",
        "/industries/yacht/coastal-spirit/gallery-twilight.png",
        "/industries/yacht/coastal-spirit/gallery-texture.png",
      ],
      appreciation: 0,
      attributes: {
        length: 18,
        guests: 6,
        cabins: 3,
        crewed: false,
        waterToys: true,
        crewSize: 0,
      },
      highlights: ["Bareboat or skippered", "Best value on the coast", "Jet skis included"],
    },
  ],
  ruleSpecs: [
    { id: "budget-fit", kind: "budget", questionId: "budget", weight: 3 },
    {
      id: "guests-min",
      kind: "atLeast",
      questionId: "guests",
      attribute: "guests",
      weight: 2.5,
      reason: "it sleeps {have} guests, covering your party of {need}",
    },
    {
      id: "crewed",
      kind: "feature",
      questionId: "crewed",
      attribute: "crewed",
      weight: 2.5,
      reason: "it comes fully crewed as you wanted",
    },
    {
      id: "water-toys",
      kind: "feature",
      questionId: "waterToys",
      attribute: "waterToys",
      weight: 2,
      reason: "it carries a full water toys package",
    },
  ],
  rules: [],
};

yachtPack.rules = compileRules(yachtPack.ruleSpecs!);
