import { NextResponse } from "next/server";
import { getPack } from "@/core/industries";
import { scoreInventory } from "@/core/engine/scoring";
import { narrate, buildNarrationPrompt } from "@/core/engine/explain";
import type { Answers } from "@/core/types";

/**
 * AI Decision Engine endpoint.
 *
 * POST { packId, answers } -> ranked, self-explaining recommendations.
 *
 * Today it runs the deterministic engine (works offline, zero latency). To
 * upgrade a tenant to LLM-authored narratives, set ANTHROPIC_API_KEY and flip
 * `useLLM`: the scoring/ranking stays identical — only the narrative prose is
 * generated by Claude from the *verified* reasons, so it can never hallucinate
 * facts. `buildNarrationPrompt` is the exact prompt that would be sent.
 */
export async function POST(request: Request) {
  let body: { packId?: string; answers?: Answers };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const pack = getPack(body.packId);
  const answers = body.answers ?? {};
  const scored = scoreInventory(pack, answers);

  const useLLM = false; // seam: enable when ANTHROPIC_API_KEY is configured

  const recommendations = scored.slice(0, 5).map((s) => ({
    id: s.item.id,
    name: s.item.name,
    subtitle: s.item.subtitle,
    price: s.item.price,
    currency: s.item.currency,
    score: s.score,
    reasons: s.reasons,
    narrative: narrate(s, pack),
    // Included so callers can inspect or route to an LLM downstream.
    llmPrompt: useLLM ? buildNarrationPrompt(s, pack) : undefined,
  }));

  return NextResponse.json({
    packId: pack.id,
    vertical: pack.vertical,
    engine: useLLM ? "claude+scoring" : "deterministic-scoring",
    recommendations,
  });
}
